apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-mvn-app
  labels:
    app: mvn-app
  annotations:
    purpose: "helloworld"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvn-app
  template:
    metadata:
      labels:
        app: mvn-app
    spec:
      containers:
      - name: sample-mvn-app
        image: abhidhingra/jenkins-ts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
