apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    purpose: helloworld
  labels:
    app: mvn-app
    app.kubernetes.io/instance: samplemvn
  name: sample-mvn-app
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvn-app
  template:
    metadata:
      labels:
        app: mvn-app
    spec:
      containers:
        - image: 'abhidhingra/jenkins-ts:1.0'
          imagePullPolicy: IfNotPresent
          name: sample-mvn-app
          ports:
            - containerPort: 80
